#############################################################################
# Makefile for building: libgsoc2014.so
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  minimal.pro
# Template: app
# Command: /home/reingart/qt/5.2.1/android_armv5/bin/qmake -o Makefile minimal.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /home/reingart/src/android-ndk-r9d/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
CXX           = /home/reingart/src/android-ndk-r9d/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++
DEFINES       = -DQT_OS_ANDROID_GCC_48_WORKAROUND -D__WXQT__ -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -Wno-psabi -march=armv5te -mtune=xscale -msoft-float -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums -DANDROID -Wa,--noexecstack -g -gdwarf-2 -marm -O0 -fno-omit-frame-pointer -Wall -Wno-psabi -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -Wno-psabi -march=armv5te -mtune=xscale -msoft-float -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums -DANDROID -Wa,--noexecstack -std=gnu++0x -g -g -gdwarf-2 -marm -O0 -fno-omit-frame-pointer -Wall -Wno-psabi -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../qt/5.2.1/android_armv5/mkspecs/android-g++ -I. -I../src/wxWidgets/include -I../src/wxWidgets/android/lib/wx/include/arm-linux-androideabi-qt-unicode-static-2.9 -I../qt/5.2.1/android_armv5/include -I../qt/5.2.1/android_armv5/include/QtWidgets -I../qt/5.2.1/android_armv5/include/QtGui -I../qt/5.2.1/android_armv5/include/QtCore -I. -I../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include -I../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi/include -I../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include
LINK          = /home/reingart/src/android-ndk-r9d/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++
LFLAGS        = --sysroot=/home/reingart/src/android-ndk-r9d/platforms/android-9/arch-arm/ -Wl,-soname,libgsoc2014.so -Wl,-rpath=/home/reingart/qt/5.2.1/android_armv5/lib -Wl,--no-undefined -Wl,-z,noexecstack -shared
LIBS          = $(SUBLIBS) -L/home/reingart/src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi -L/home/reingart/src/android-ndk-r9d/platforms/android-9/arch-arm//usr/lib /home/reingart/src/wxWidgets/android/lib/libwx_qtu_qa-2.9-arm-linux-androideabi.a /home/reingart/src/wxWidgets/android/lib/libwx_qtu_adv-2.9-arm-linux-androideabi.a /home/reingart/src/wxWidgets/android/lib/libwx_qtu_core-2.9-arm-linux-androideabi.a /home/reingart/src/wxWidgets/android/lib/libwx_baseu-2.9-arm-linux-androideabi.a -L/home/reingart/src/wxWidgets/android/lib -L/home/reingart/qt/5.2.1/android_armv5/lib -lQt5Widgets -L/opt/android/ndk/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi -L/opt/android/ndk/platforms/android-9/arch-arm//usr/lib -lQt5Gui -lQt5Core -lGLESv2 -lgnustl_shared -llog -lz -lm -ldl -lc -lgcc
AR            = /home/reingart/src/android-ndk-r9d/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar cqs
RANLIB        = /home/reingart/src/android-ndk-r9d/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ranlib
QMAKE         = /home/reingart/qt/5.2.1/android_armv5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = minimal.cpp 
OBJECTS       = minimal.o
DIST          = ../qt/5.2.1/android_armv5/mkspecs/features/spec_pre.prf \
		../qt/5.2.1/android_armv5/mkspecs/common/shell-unix.conf \
		../qt/5.2.1/android_armv5/mkspecs/common/unix.conf \
		../qt/5.2.1/android_armv5/mkspecs/common/linux.conf \
		../qt/5.2.1/android_armv5/mkspecs/common/gcc-base.conf \
		../qt/5.2.1/android_armv5/mkspecs/common/gcc-base-unix.conf \
		../qt/5.2.1/android_armv5/mkspecs/qdevice.pri \
		../qt/5.2.1/android_armv5/mkspecs/features/device_config.prf \
		../qt/5.2.1/android_armv5/mkspecs/qconfig.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_androidextras.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_androidextras_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_bluetooth.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_clucene_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_concurrent.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_core.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_core_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_declarative.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_declarative_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_gui.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_gui_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_help.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_help_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_multimedia.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_multimedia_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_network.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_network_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_nfc.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_nfc_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_opengl.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_opengl_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_openglextensions.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_positioning.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_positioning_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_printsupport.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_qml.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_qml_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_qmltest.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_qmltest_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_quick.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_quick_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_script.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_script_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_scripttools.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_scripttools_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_sensors.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_sensors_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_sql.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_sql_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_svg.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_svg_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_testlib.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_testlib_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_uitools.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_uitools_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_widgets.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_widgets_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_xml.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_xml_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/features/qt_functions.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/qt_config.prf \
		../qt/5.2.1/android_armv5/mkspecs/android-g++/qmake.conf \
		../qt/5.2.1/android_armv5/mkspecs/features/spec_post.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/exclusive_builds.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/default_pre.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/resolve_config.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/default_post.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/android/android.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/android/android_deployment_settings.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/warn_on.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/qt.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/resources.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/moc.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/unix/opengl.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/uic.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/unix/thread.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/testcase_targets.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/exceptions.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/yacc.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/lex.prf \
		minimal.pro \
		minimal.pro
QMAKE_TARGET  = libgsoc2014.so
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = libgsoc2014.so


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: minimal.pro ../qt/5.2.1/android_armv5/mkspecs/android-g++/qmake.conf ../qt/5.2.1/android_armv5/mkspecs/features/spec_pre.prf \
		../qt/5.2.1/android_armv5/mkspecs/common/shell-unix.conf \
		../qt/5.2.1/android_armv5/mkspecs/common/unix.conf \
		../qt/5.2.1/android_armv5/mkspecs/common/linux.conf \
		../qt/5.2.1/android_armv5/mkspecs/common/gcc-base.conf \
		../qt/5.2.1/android_armv5/mkspecs/common/gcc-base-unix.conf \
		../qt/5.2.1/android_armv5/mkspecs/qdevice.pri \
		../qt/5.2.1/android_armv5/mkspecs/features/device_config.prf \
		../qt/5.2.1/android_armv5/mkspecs/qconfig.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_androidextras.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_androidextras_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_bluetooth.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_clucene_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_concurrent.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_core.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_core_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_declarative.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_declarative_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_gui.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_gui_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_help.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_help_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_multimedia.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_multimedia_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_network.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_network_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_nfc.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_nfc_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_opengl.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_opengl_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_openglextensions.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_positioning.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_positioning_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_printsupport.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_qml.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_qml_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_qmltest.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_qmltest_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_quick.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_quick_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_script.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_script_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_scripttools.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_scripttools_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_sensors.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_sensors_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_sql.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_sql_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_svg.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_svg_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_testlib.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_testlib_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_uitools.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_uitools_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_widgets.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_widgets_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_xml.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_xml_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../qt/5.2.1/android_armv5/mkspecs/features/qt_functions.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/qt_config.prf \
		../qt/5.2.1/android_armv5/mkspecs/android-g++/qmake.conf \
		../qt/5.2.1/android_armv5/mkspecs/features/spec_post.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/exclusive_builds.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/default_pre.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/resolve_config.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/default_post.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/android/android.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/android/android_deployment_settings.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/warn_on.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/qt.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/resources.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/moc.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/unix/opengl.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/uic.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/unix/thread.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/testcase_targets.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/exceptions.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/yacc.prf \
		../qt/5.2.1/android_armv5/mkspecs/features/lex.prf \
		minimal.pro \
		/home/reingart/qt/5.2.1/android_armv5/lib/libQt5Widgets.prl \
		/home/reingart/qt/5.2.1/android_armv5/lib/libQt5Gui.prl \
		/home/reingart/qt/5.2.1/android_armv5/lib/libQt5Core.prl
	$(QMAKE) -o Makefile minimal.pro
../qt/5.2.1/android_armv5/mkspecs/features/spec_pre.prf:
../qt/5.2.1/android_armv5/mkspecs/common/shell-unix.conf:
../qt/5.2.1/android_armv5/mkspecs/common/unix.conf:
../qt/5.2.1/android_armv5/mkspecs/common/linux.conf:
../qt/5.2.1/android_armv5/mkspecs/common/gcc-base.conf:
../qt/5.2.1/android_armv5/mkspecs/common/gcc-base-unix.conf:
../qt/5.2.1/android_armv5/mkspecs/qdevice.pri:
../qt/5.2.1/android_armv5/mkspecs/features/device_config.prf:
../qt/5.2.1/android_armv5/mkspecs/qconfig.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_androidextras.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_androidextras_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_bluetooth.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_bluetooth_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_bootstrap_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_clucene_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_concurrent.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_concurrent_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_core.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_core_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_declarative.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_declarative_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_gui.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_gui_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_help.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_help_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_multimedia.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_multimedia_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_multimediawidgets.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_network.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_network_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_nfc.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_nfc_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_opengl.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_opengl_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_openglextensions.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_openglextensions_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_platformsupport_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_positioning.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_positioning_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_printsupport.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_printsupport_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_qml.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_qml_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_qmltest.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_qmltest_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_quick.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_quick_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_quickparticles_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_script.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_script_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_scripttools.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_scripttools_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_sensors.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_sensors_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_sql.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_sql_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_svg.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_svg_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_testlib.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_testlib_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_uitools.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_uitools_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_widgets.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_widgets_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_xml.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_xml_private.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_xmlpatterns.pri:
../qt/5.2.1/android_armv5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../qt/5.2.1/android_armv5/mkspecs/features/qt_functions.prf:
../qt/5.2.1/android_armv5/mkspecs/features/qt_config.prf:
../qt/5.2.1/android_armv5/mkspecs/android-g++/qmake.conf:
../qt/5.2.1/android_armv5/mkspecs/features/spec_post.prf:
../qt/5.2.1/android_armv5/mkspecs/features/exclusive_builds.prf:
../qt/5.2.1/android_armv5/mkspecs/features/default_pre.prf:
../qt/5.2.1/android_armv5/mkspecs/features/resolve_config.prf:
../qt/5.2.1/android_armv5/mkspecs/features/default_post.prf:
../qt/5.2.1/android_armv5/mkspecs/features/android/android.prf:
../qt/5.2.1/android_armv5/mkspecs/features/android/android_deployment_settings.prf:
../qt/5.2.1/android_armv5/mkspecs/features/warn_on.prf:
../qt/5.2.1/android_armv5/mkspecs/features/qt.prf:
../qt/5.2.1/android_armv5/mkspecs/features/resources.prf:
../qt/5.2.1/android_armv5/mkspecs/features/moc.prf:
../qt/5.2.1/android_armv5/mkspecs/features/unix/opengl.prf:
../qt/5.2.1/android_armv5/mkspecs/features/uic.prf:
../qt/5.2.1/android_armv5/mkspecs/features/unix/thread.prf:
../qt/5.2.1/android_armv5/mkspecs/features/testcase_targets.prf:
../qt/5.2.1/android_armv5/mkspecs/features/exceptions.prf:
../qt/5.2.1/android_armv5/mkspecs/features/yacc.prf:
../qt/5.2.1/android_armv5/mkspecs/features/lex.prf:
minimal.pro:
/home/reingart/qt/5.2.1/android_armv5/lib/libQt5Widgets.prl:
/home/reingart/qt/5.2.1/android_armv5/lib/libQt5Gui.prl:
/home/reingart/qt/5.2.1/android_armv5/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile minimal.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/libgsoc2014.so1.0.0 || mkdir -p .tmp/libgsoc2014.so1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/libgsoc2014.so1.0.0/ && $(COPY_FILE) --parents minimal.cpp .tmp/libgsoc2014.so1.0.0/ && (cd `dirname .tmp/libgsoc2014.so1.0.0` && $(TAR) libgsoc2014.so1.0.0.tar libgsoc2014.so1.0.0 && $(COMPRESS) libgsoc2014.so1.0.0.tar) && $(MOVE) `dirname .tmp/libgsoc2014.so1.0.0`/libgsoc2014.so1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/libgsoc2014.so1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

minimal.o: minimal.cpp ../src/wxWidgets/include/wx/wxprec.h \
		../src/wxWidgets/include/wx/defs.h \
		../src/wxWidgets/include/wx/platform.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/unistd.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/sys/cdefs.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/sys/cdefs_elf.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/android/api-level.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/sys/types.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/stdint.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/sys/_types.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/machine/_types.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/sys/_wchar_limits.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/linux/posix_types.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/linux/stddef.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/linux/compiler.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/asm/posix_types.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/asm/types.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/linux/types.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/machine/kernel.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/sys/sysmacros.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/sys/select.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/sys/time.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/linux/time.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/signal.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/limits.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/sys/limits.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/linux/limits.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/machine/internal_types.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/machine/limits.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/sys/syslimits.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/asm/page.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/string.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/malloc.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/asm/signal.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/asm-generic/signal.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/asm/sigcontext.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/asm/siginfo.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/asm-generic/siginfo.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/sys/sysconf.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/linux/capability.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/pathconf.h \
		../src/wxWidgets/include/wx/osx/config_xcode.h \
		../src/wxWidgets/android/lib/wx/include/arm-linux-androideabi-qt-unicode-static-2.9/wx/setup.h \
		../src/wxWidgets/include/wx/setup_gccxml.h \
		../src/wxWidgets/include/wx/msw/wince/libraries.h \
		../src/wxWidgets/include/wx/msw/libraries.h \
		../src/wxWidgets/include/wx/msw/gccpriv.h \
		../src/wxWidgets/include/wx/chkconf.h \
		../src/wxWidgets/include/wx/palmos/chkconf.h \
		../src/wxWidgets/include/wx/msw/wince/chkconf.h \
		../src/wxWidgets/include/wx/msw/chkconf.h \
		../src/wxWidgets/include/wx/gtk/chkconf.h \
		../src/wxWidgets/include/wx/cocoa/chkconf.h \
		../src/wxWidgets/include/wx/osx/chkconf.h \
		../src/wxWidgets/include/wx/osx/iphone/chkconf.h \
		../src/wxWidgets/include/wx/osx/carbon/chkconf.h \
		../src/wxWidgets/include/wx/osx/cocoa/chkconf.h \
		../src/wxWidgets/include/wx/os2/chkconf.h \
		../src/wxWidgets/include/wx/mgl/chkconf.h \
		../src/wxWidgets/include/wx/dfb/chkconf.h \
		../src/wxWidgets/include/wx/motif/chkconf.h \
		../src/wxWidgets/include/wx/x11/chkconf.h \
		../src/wxWidgets/include/wx/unix/chkconf.h \
		../src/wxWidgets/include/wx/univ/chkconf.h \
		../src/wxWidgets/include/wx/palmos/missing.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/stdio.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/stdlib.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/alloca.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/strings.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/memory.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/wchar.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/time.h \
		../src/wxWidgets/include/wx/version.h \
		../src/wxWidgets/include/wx/cpp.h \
		../src/wxWidgets/include/wx/dlimpexp.h \
		../src/wxWidgets/include/wx/debug.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/assert.h \
		../src/wxWidgets/include/wx/chartype.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/ctype.h \
		../src/wxWidgets/include/wx/windowid.h \
		../src/wxWidgets/include/wx/qt/defs.h \
		../src/wxWidgets/include/wx/msw/winundef.h \
		../src/wxWidgets/include/wx/features.h \
		../src/wxWidgets/include/wx/msw/wrapwin.h \
		../src/wxWidgets/include/wx/msw/wrapcctl.h \
		../src/wxWidgets/include/wx/msw/missing.h \
		../src/wxWidgets/include/wx/msw/wince/missing.h \
		../src/wxWidgets/include/wx/msw/private.h \
		../src/wxWidgets/include/wx/msw/microwin.h \
		../src/wxWidgets/include/wx/log.h \
		../src/wxWidgets/include/wx/string.h \
		../src/wxWidgets/include/wx/wxcrtbase.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/wctype.h \
		../src/wxWidgets/include/wx/strvararg.h \
		../src/wxWidgets/include/wx/strconv.h \
		../src/wxWidgets/include/wx/buffer.h \
		../src/wxWidgets/include/wx/typeinfo.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/typeinfo \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/exception \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi/include/bits/c++config.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi/include/bits/os_defines.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi/include/bits/cpu_defines.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/atomic_lockfree_defines.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/exception_ptr.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/exception_defines.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/nested_exception.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/c++0x_warning.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/hash_bytes.h \
		../src/wxWidgets/include/wx/fontenc.h \
		../src/wxWidgets/include/wx/unichar.h \
		../src/wxWidgets/include/wx/stringimpl.h \
		../src/wxWidgets/include/wx/beforestd.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/string \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stringfwd.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/memoryfwd.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/char_traits.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_algobase.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/functexcept.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/cpp_type_traits.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/ext/type_traits.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/ext/numeric_traits.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_pair.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/move.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/concept_check.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/boost_concept_check.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_iterator_base_types.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/type_traits \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_iterator_base_funcs.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/debug.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/macros.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/functions.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/formatter.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_iterator.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/algobase.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/base.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_function.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/backward/binders.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/features.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/basic_iterator.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/parallel.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/compiletime_settings.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/cstdio \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/types.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/cstdlib \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/limits \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/cstdint \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/tags.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/settings.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/algorithmfwd.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/find.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/compatibility.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/sched.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/equally_split.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/find_selectors.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/postypes.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/cwchar \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/cstdint \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/allocator.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi/include/bits/c++allocator.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/ext/new_allocator.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/new \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/localefwd.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi/include/bits/c++locale.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/clocale \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/locale.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/iosfwd \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/cctype \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/ostream_insert.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/cxxabi_forced.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/range_access.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/basic_string.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/ext/atomicity.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi/include/bits/gthr.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi/include/bits/gthr-default.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/pthread.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi/include/bits/atomic_word.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/initializer_list \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/ext/string_conversions.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/cerrno \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/errno.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/linux/errno.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/asm/errno.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/asm-generic/errno.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/asm-generic/errno-base.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/functional_hash.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/basic_string.tcc \
		../src/wxWidgets/include/wx/afterstd.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/type_traits \
		../src/wxWidgets/include/wx/stringops.h \
		../src/wxWidgets/include/wx/tls.h \
		../src/wxWidgets/include/wx/msw/tls.h \
		../src/wxWidgets/include/wx/thread.h \
		../src/wxWidgets/include/wx/vector.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/vector \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_construct.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/ext/alloc_traits.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/alloc_traits.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/ptr_traits.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_uninitialized.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_vector.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_bvector.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/vector.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/vector \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/utility \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_relops.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/safe_sequence.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/safe_base.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/ext/concurrence.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/safe_sequence.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/safe_iterator.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/safe_iterator.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/vector \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/base.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/functional \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tuple \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/array \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/stdexcept \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/array \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/array \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/uses_allocator.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/impl/profiler.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/impl/profiler_hash_func.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/impl/profiler_node.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/impl/profiler_trace.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/unordered_map \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/hashtable.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/hashtable_policy.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/unordered_map.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/unordered_map \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/safe_unordered_container.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/safe_unordered_base.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/safe_unordered_container.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/safe_local_iterator.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/safe_local_iterator.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/unordered_map \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/unordered_base.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/unordered_map \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/functional_hash.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/hashtable.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/hashtable_policy.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/unordered_map.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/fstream \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/istream \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/ios \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/ios_base.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/locale_classes.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/locale_classes.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/streambuf \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/streambuf.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/basic_ios.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/locale_facets.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/cwctype \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi/include/bits/ctype_base.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/streambuf_iterator.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi/include/bits/ctype_inline.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/locale_facets.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/basic_ios.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/ostream \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/ostream.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/istream.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/codecvt.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi/include/bits/basic_file.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi/include/bits/c++io.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/fstream.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/impl/profiler_algos.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/impl/profiler_state.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/impl/profiler_hashtable_size.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/impl/profiler_container_size.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/sstream \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/sstream.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/impl/profiler_map_to_unordered_map.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/impl/profiler_vector_size.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/impl/profiler_vector_to_list.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/impl/profiler_list_to_slist.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/impl/profiler_list_to_vector.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/iterator_tracker.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/algorithm \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_algo.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/algorithmfwd.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_heap.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_tempbuf.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/random \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/cmath \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/math.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/random.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/opt_random.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/random.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/numeric \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_numeric.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/numeric \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/numericfwd.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/iterator.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/for_each.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/par_loop.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/omp_loop.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/workstealing.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/random_number.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/random \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/cmath \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/gamma.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/special_function_util.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/bessel_function.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/beta_function.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/ell_integral.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/exp_integral.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/hypergeometric.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/legendre_function.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/modified_bessel_func.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/poly_hermite.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/poly_laguerre.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/riemann_zeta.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/random.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/tr1/random.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/for_each_selectors.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/partial_sum.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/algorithm \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/algo.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/sort.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/checkers.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/multiway_mergesort.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/multiway_merge.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/losertree.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/multiseq_selection.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/queue \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/deque \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_deque.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/deque.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/deque \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/deque \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_queue.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/quicksort.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/partition.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/balanced_quicksort.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/queue.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/omp_loop_static.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/search.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/random_shuffle.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/merge.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/unique_copy.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/parallel/set_operations.h \
		../src/wxWidgets/include/wx/utils.h \
		../src/wxWidgets/include/wx/object.h \
		../src/wxWidgets/include/wx/memory.h \
		../src/wxWidgets/include/wx/msgout.h \
		../src/wxWidgets/include/wx/xti.h \
		../src/wxWidgets/include/wx/xtitypes.h \
		../src/wxWidgets/include/wx/hashmap.h \
		../src/wxWidgets/include/wx/wxcrt.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/ext/hash_map \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/backward/hashtable.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/iterator \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stream_iterator.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/backward/hash_fun.h \
		../src/wxWidgets/include/wx/arrstr.h \
		../src/wxWidgets/include/wx/dynarray.h \
		../src/wxWidgets/include/wx/flags.h \
		../src/wxWidgets/include/wx/intl.h \
		../src/wxWidgets/include/wx/translation.h \
		../src/wxWidgets/include/wx/language.h \
		../src/wxWidgets/include/wx/scopedptr.h \
		../src/wxWidgets/include/wx/checkeddelete.h \
		../src/wxWidgets/include/wx/xtihandler.h \
		../src/wxWidgets/include/wx/rtti.h \
		../src/wxWidgets/include/wx/xti2.h \
		../src/wxWidgets/include/wx/xtiprop.h \
		../src/wxWidgets/include/wx/any.h \
		../src/wxWidgets/include/wx/meta/if.h \
		../src/wxWidgets/include/wx/list.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/list \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_list.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/list.tcc \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/list \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/list \
		../src/wxWidgets/include/wx/datetime.h \
		../src/wxWidgets/include/wx/msw/wince/time.h \
		../src/wxWidgets/include/wx/longlong.h \
		../src/wxWidgets/include/wx/iosfwrap.h \
		../src/wxWidgets/include/wx/anystr.h \
		../src/wxWidgets/include/wx/variant.h \
		../src/wxWidgets/include/wx/xtictor.h \
		../src/wxWidgets/include/wx/msw/msvcrt.h \
		../src/wxWidgets/include/wx/filefn.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/sys/stat.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/linux/stat.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/endian.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/sys/endian.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/machine/endian.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/utime.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/linux/utime.h \
		../src/wxWidgets/include/wx/os2/private.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/dirent.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/fcntl.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/linux/fcntl.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/asm/fcntl.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/asm-generic/fcntl.h \
		../src/wxWidgets/include/wx/versioninfo.h \
		../src/wxWidgets/include/wx/meta/implicitconversion.h \
		../src/wxWidgets/include/wx/gdicmn.h \
		../src/wxWidgets/include/wx/math.h \
		../src/wxWidgets/include/wx/mousestate.h \
		../src/wxWidgets/include/wx/kbdstate.h \
		../src/wxWidgets/include/wx/platinfo.h \
		../src/wxWidgets/include/wx/scopeguard.h \
		../src/wxWidgets/include/wx/except.h \
		../src/wxWidgets/include/wx/meta/movable.h \
		../src/wxWidgets/include/wx/meta/pod.h \
		../src/wxWidgets/include/wx/os2/tls.h \
		../src/wxWidgets/include/wx/unix/tls.h \
		../src/wxWidgets/include/wx/crt.h \
		../src/wxWidgets/include/wx/wxcrtvararg.h \
		../src/wxWidgets/include/wx/generic/logg.h \
		../src/wxWidgets/include/wx/cocoa/log.h \
		../src/wxWidgets/include/wx/window.h \
		../src/wxWidgets/include/wx/event.h \
		../src/wxWidgets/include/wx/clntdata.h \
		../src/wxWidgets/include/wx/cursor.h \
		../src/wxWidgets/include/wx/palmos/cursor.h \
		../src/wxWidgets/include/wx/palmos/gdiimage.h \
		../src/wxWidgets/include/wx/gdiobj.h \
		../src/wxWidgets/include/wx/msw/cursor.h \
		../src/wxWidgets/include/wx/msw/gdiimage.h \
		../src/wxWidgets/include/wx/motif/cursor.h \
		../src/wxWidgets/include/wx/gtk/cursor.h \
		../src/wxWidgets/include/wx/gtk1/cursor.h \
		../src/wxWidgets/include/wx/image.h \
		../src/wxWidgets/include/wx/stream.h \
		../src/wxWidgets/include/wx/imagbmp.h \
		../src/wxWidgets/include/wx/imagpng.h \
		../src/wxWidgets/include/wx/imaggif.h \
		../src/wxWidgets/include/wx/imagpcx.h \
		../src/wxWidgets/include/wx/imagjpeg.h \
		../src/wxWidgets/include/wx/imagtga.h \
		../src/wxWidgets/include/wx/imagtiff.h \
		../src/wxWidgets/include/wx/imagpnm.h \
		../src/wxWidgets/include/wx/imagxpm.h \
		../src/wxWidgets/include/wx/imagiff.h \
		../src/wxWidgets/include/wx/x11/cursor.h \
		../src/wxWidgets/include/wx/colour.h \
		../src/wxWidgets/include/wx/generic/colour.h \
		../src/wxWidgets/include/wx/msw/colour.h \
		../src/wxWidgets/include/wx/motif/colour.h \
		../src/wxWidgets/include/wx/gtk/colour.h \
		../src/wxWidgets/include/wx/gtk1/colour.h \
		../src/wxWidgets/include/wx/palette.h \
		../src/wxWidgets/include/wx/palmos/palette.h \
		../src/wxWidgets/include/wx/msw/palette.h \
		../src/wxWidgets/include/wx/x11/palette.h \
		../src/wxWidgets/include/wx/generic/paletteg.h \
		../src/wxWidgets/include/wx/mgl/palette.h \
		../src/wxWidgets/include/wx/osx/palette.h \
		../src/wxWidgets/include/wx/os2/palette.h \
		../src/wxWidgets/include/wx/qt/palette.h \
		../src/wxWidgets/include/wx/x11/colour.h \
		../src/wxWidgets/include/wx/osx/colour.h \
		../src/wxWidgets/include/wx/osx/core/colour.h \
		../src/wxWidgets/include/wx/osx/core/cfref.h \
		../src/wxWidgets/include/wx/cocoa/colour.h \
		../src/wxWidgets/include/wx/os2/colour.h \
		../src/wxWidgets/include/wx/qt/colour.h \
		../qt/5.2.1/android_armv5/include/QtGui/QColor \
		../qt/5.2.1/android_armv5/include/QtGui/qcolor.h \
		../qt/5.2.1/android_armv5/include/QtGui/qrgb.h \
		../qt/5.2.1/android_armv5/include/QtCore/qglobal.h \
		../qt/5.2.1/android_armv5/include/QtCore/qconfig.h \
		../qt/5.2.1/android_armv5/include/QtCore/qfeatures.h \
		../qt/5.2.1/android_armv5/include/QtCore/qsystemdetection.h \
		../qt/5.2.1/android_armv5/include/QtCore/qprocessordetection.h \
		../qt/5.2.1/android_armv5/include/QtCore/qcompilerdetection.h \
		../qt/5.2.1/android_armv5/include/QtCore/qglobalstatic.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic.h \
		../qt/5.2.1/android_armv5/include/QtCore/qbasicatomic.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic_bootstrap.h \
		../qt/5.2.1/android_armv5/include/QtCore/qgenericatomic.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic_msvc.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic_integrity.h \
		../qt/5.2.1/android_armv5/include/QtCore/qoldbasicatomic.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic_vxworks.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic_power.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic_alpha.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic_armv7.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic_armv6.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic_armv5.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic_bfin.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic_ia64.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic_mips.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic_s390.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic_sh4a.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic_sparc.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic_x86.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic_cxx11.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/atomic \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/atomic_base.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic_gcc.h \
		../qt/5.2.1/android_armv5/include/QtCore/qatomic_unix.h \
		../qt/5.2.1/android_armv5/include/QtCore/qmutex.h \
		../qt/5.2.1/android_armv5/include/QtCore/qlogging.h \
		../qt/5.2.1/android_armv5/include/QtCore/qflags.h \
		../qt/5.2.1/android_armv5/include/QtCore/qtypeinfo.h \
		../qt/5.2.1/android_armv5/include/QtCore/qtypetraits.h \
		../qt/5.2.1/android_armv5/include/QtCore/qsysinfo.h \
		../qt/5.2.1/android_armv5/include/QtCore/qnamespace.h \
		../qt/5.2.1/android_armv5/include/QtCore/qstringlist.h \
		../qt/5.2.1/android_armv5/include/QtCore/qalgorithms.h \
		../qt/5.2.1/android_armv5/include/QtCore/qdatastream.h \
		../qt/5.2.1/android_armv5/include/QtCore/qscopedpointer.h \
		../qt/5.2.1/android_armv5/include/QtCore/qiodevice.h \
		../qt/5.2.1/android_armv5/include/QtCore/qobject.h \
		../qt/5.2.1/android_armv5/include/QtCore/qobjectdefs.h \
		../qt/5.2.1/android_armv5/include/QtCore/qobjectdefs_impl.h \
		../qt/5.2.1/android_armv5/include/QtCore/qstring.h \
		../qt/5.2.1/android_armv5/include/QtCore/qchar.h \
		../qt/5.2.1/android_armv5/include/QtCore/qbytearray.h \
		../qt/5.2.1/android_armv5/include/QtCore/qrefcount.h \
		../qt/5.2.1/android_armv5/include/QtCore/qarraydata.h \
		../qt/5.2.1/android_armv5/include/QtCore/qstringbuilder.h \
		../qt/5.2.1/android_armv5/include/QtCore/qlist.h \
		../qt/5.2.1/android_armv5/include/QtCore/qiterator.h \
		../qt/5.2.1/android_armv5/include/QtCore/qcoreevent.h \
		../qt/5.2.1/android_armv5/include/QtCore/qmetatype.h \
		../qt/5.2.1/android_armv5/include/QtCore/qvarlengtharray.h \
		../qt/5.2.1/android_armv5/include/QtCore/qcontainerfwd.h \
		../qt/5.2.1/android_armv5/include/QtCore/qisenum.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/map \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_tree.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_map.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/stl_multimap.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/map \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/map.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/debug/multimap.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/map \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/map.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/profile/multimap.h \
		../qt/5.2.1/android_armv5/include/QtCore/qobject_impl.h \
		../qt/5.2.1/android_armv5/include/QtCore/qpair.h \
		../qt/5.2.1/android_armv5/include/QtCore/qregexp.h \
		../qt/5.2.1/android_armv5/include/QtCore/qstringmatcher.h \
		../src/wxWidgets/include/wx/mgl/cursor.h \
		../src/wxWidgets/include/wx/dfb/cursor.h \
		../src/wxWidgets/include/wx/osx/cursor.h \
		../src/wxWidgets/include/wx/bitmap.h \
		../src/wxWidgets/include/wx/palmos/bitmap.h \
		../src/wxWidgets/include/wx/msw/bitmap.h \
		../src/wxWidgets/include/wx/x11/bitmap.h \
		../src/wxWidgets/include/wx/gtk/bitmap.h \
		../src/wxWidgets/include/wx/gtk1/bitmap.h \
		../src/wxWidgets/include/wx/mgl/bitmap.h \
		../src/wxWidgets/include/wx/dfb/bitmap.h \
		../src/wxWidgets/include/wx/dfb/dfbptr.h \
		../src/wxWidgets/include/wx/osx/bitmap.h \
		../src/wxWidgets/include/wx/cocoa/bitmap.h \
		../src/wxWidgets/include/wx/os2/bitmap.h \
		../src/wxWidgets/include/wx/os2/gdiimage.h \
		../src/wxWidgets/include/wx/qt/bitmap.h \
		../src/wxWidgets/include/wx/generic/mask.h \
		../src/wxWidgets/include/wx/cocoa/cursor.h \
		../src/wxWidgets/include/wx/os2/cursor.h \
		../src/wxWidgets/include/wx/qt/cursor.h \
		../qt/5.2.1/android_armv5/include/QtGui/QCursor \
		../qt/5.2.1/android_armv5/include/QtGui/qcursor.h \
		../qt/5.2.1/android_armv5/include/QtCore/qpoint.h \
		../qt/5.2.1/android_armv5/include/QtGui/qwindowdefs.h \
		../qt/5.2.1/android_armv5/include/QtGui/qwindowdefs_win.h \
		../src/wxWidgets/include/wx/tracker.h \
		../src/wxWidgets/include/wx/meta/convertible.h \
		../src/wxWidgets/include/wx/font.h \
		../src/wxWidgets/include/wx/palmos/font.h \
		../src/wxWidgets/include/wx/msw/font.h \
		../src/wxWidgets/include/wx/motif/font.h \
		../src/wxWidgets/include/wx/gtk/font.h \
		../src/wxWidgets/include/wx/gtk1/font.h \
		../src/wxWidgets/include/wx/hash.h \
		../src/wxWidgets/include/wx/x11/font.h \
		../src/wxWidgets/include/wx/mgl/font.h \
		../src/wxWidgets/include/wx/dfb/font.h \
		../src/wxWidgets/include/wx/osx/font.h \
		../src/wxWidgets/include/wx/cocoa/font.h \
		../src/wxWidgets/include/wx/os2/font.h \
		../src/wxWidgets/include/wx/qt/font.h \
		../src/wxWidgets/include/wx/region.h \
		../src/wxWidgets/include/wx/palmos/region.h \
		../src/wxWidgets/include/wx/msw/region.h \
		../src/wxWidgets/include/wx/gtk/region.h \
		../src/wxWidgets/include/wx/gtk1/region.h \
		../src/wxWidgets/include/wx/x11/region.h \
		../src/wxWidgets/include/wx/mgl/region.h \
		../src/wxWidgets/include/wx/dfb/region.h \
		../src/wxWidgets/include/wx/osx/region.h \
		../src/wxWidgets/include/wx/osx/carbon/region.h \
		../src/wxWidgets/include/wx/generic/region.h \
		../src/wxWidgets/include/wx/cocoa/region.h \
		../src/wxWidgets/include/wx/os2/region.h \
		../src/wxWidgets/include/wx/qt/region.h \
		../qt/5.2.1/android_armv5/include/QtGui/QRegion \
		../qt/5.2.1/android_armv5/include/QtGui/qregion.h \
		../qt/5.2.1/android_armv5/include/QtCore/qrect.h \
		../qt/5.2.1/android_armv5/include/QtCore/qsize.h \
		../src/wxWidgets/include/wx/validate.h \
		../src/wxWidgets/include/wx/accel.h \
		../src/wxWidgets/include/wx/generic/accel.h \
		../src/wxWidgets/include/wx/msw/accel.h \
		../src/wxWidgets/include/wx/motif/accel.h \
		../src/wxWidgets/include/wx/gtk/accel.h \
		../src/wxWidgets/include/wx/gtk1/accel.h \
		../src/wxWidgets/include/wx/osx/accel.h \
		../src/wxWidgets/include/wx/os2/accel.h \
		../src/wxWidgets/include/wx/qt/accel.h \
		../qt/5.2.1/android_armv5/include/QtCore/QList \
		../qt/5.2.1/android_armv5/include/QtWidgets/QShortcut \
		../qt/5.2.1/android_armv5/include/QtWidgets/qshortcut.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/qwidget.h \
		../qt/5.2.1/android_armv5/include/QtCore/qmargins.h \
		../qt/5.2.1/android_armv5/include/QtGui/qpaintdevice.h \
		../qt/5.2.1/android_armv5/include/QtGui/qpalette.h \
		../qt/5.2.1/android_armv5/include/QtGui/qbrush.h \
		../qt/5.2.1/android_armv5/include/QtCore/qvector.h \
		../qt/5.2.1/android_armv5/include/QtGui/qmatrix.h \
		../qt/5.2.1/android_armv5/include/QtGui/qpolygon.h \
		../qt/5.2.1/android_armv5/include/QtCore/qline.h \
		../qt/5.2.1/android_armv5/include/QtGui/qtransform.h \
		../qt/5.2.1/android_armv5/include/QtGui/qpainterpath.h \
		../qt/5.2.1/android_armv5/include/QtGui/qimage.h \
		../qt/5.2.1/android_armv5/include/QtGui/qpixmap.h \
		../qt/5.2.1/android_armv5/include/QtCore/qsharedpointer.h \
		../qt/5.2.1/android_armv5/include/QtCore/qshareddata.h \
		../qt/5.2.1/android_armv5/include/QtCore/qsharedpointer_impl.h \
		../qt/5.2.1/android_armv5/include/QtCore/qhash.h \
		../qt/5.2.1/android_armv5/include/QtGui/qfont.h \
		../qt/5.2.1/android_armv5/include/QtGui/qfontmetrics.h \
		../qt/5.2.1/android_armv5/include/QtGui/qfontinfo.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/qsizepolicy.h \
		../qt/5.2.1/android_armv5/include/QtGui/qkeysequence.h \
		../qt/5.2.1/android_armv5/include/QtGui/qevent.h \
		../qt/5.2.1/android_armv5/include/QtCore/qvariant.h \
		../qt/5.2.1/android_armv5/include/QtCore/qmap.h \
		../qt/5.2.1/android_armv5/include/QtCore/qdebug.h \
		../qt/5.2.1/android_armv5/include/QtCore/qtextstream.h \
		../qt/5.2.1/android_armv5/include/QtCore/qlocale.h \
		../qt/5.2.1/android_armv5/include/QtCore/qset.h \
		../qt/5.2.1/android_armv5/include/QtCore/qcontiguouscache.h \
		../qt/5.2.1/android_armv5/include/QtCore/qurl.h \
		../qt/5.2.1/android_armv5/include/QtCore/qurlquery.h \
		../qt/5.2.1/android_armv5/include/QtCore/qfile.h \
		../qt/5.2.1/android_armv5/include/QtCore/qfiledevice.h \
		../qt/5.2.1/android_armv5/include/QtGui/qvector2d.h \
		../qt/5.2.1/android_armv5/include/QtGui/qtouchdevice.h \
		../src/wxWidgets/include/wx/access.h \
		../src/wxWidgets/include/wx/msw/ole/access.h \
		../src/wxWidgets/include/wx/palmos/window.h \
		../src/wxWidgets/include/wx/msw/window.h \
		../src/wxWidgets/include/wx/settings.h \
		../src/wxWidgets/include/wx/motif/window.h \
		../src/wxWidgets/include/wx/gtk/window.h \
		../src/wxWidgets/include/wx/gtk1/window.h \
		../src/wxWidgets/include/wx/x11/window.h \
		../src/wxWidgets/include/wx/mgl/window.h \
		../src/wxWidgets/include/wx/dfb/window.h \
		../src/wxWidgets/include/wx/osx/window.h \
		../src/wxWidgets/include/wx/brush.h \
		../src/wxWidgets/include/wx/palmos/brush.h \
		../src/wxWidgets/include/wx/msw/brush.h \
		../src/wxWidgets/include/wx/x11/brush.h \
		../src/wxWidgets/include/wx/gtk/brush.h \
		../src/wxWidgets/include/wx/gtk1/brush.h \
		../src/wxWidgets/include/wx/mgl/brush.h \
		../src/wxWidgets/include/wx/dfb/brush.h \
		../src/wxWidgets/include/wx/osx/brush.h \
		../src/wxWidgets/include/wx/cocoa/brush.h \
		../src/wxWidgets/include/wx/os2/brush.h \
		../src/wxWidgets/include/wx/qt/brush.h \
		../qt/5.2.1/android_armv5/include/QtCore/Qt \
		../src/wxWidgets/include/wx/dc.h \
		../src/wxWidgets/include/wx/pen.h \
		../src/wxWidgets/include/wx/palmos/pen.h \
		../src/wxWidgets/include/wx/msw/pen.h \
		../src/wxWidgets/include/wx/x11/pen.h \
		../src/wxWidgets/include/wx/gtk/pen.h \
		../src/wxWidgets/include/wx/gtk1/pen.h \
		../src/wxWidgets/include/wx/mgl/pen.h \
		../src/wxWidgets/include/wx/dfb/pen.h \
		../src/wxWidgets/include/wx/osx/pen.h \
		../src/wxWidgets/include/wx/cocoa/pen.h \
		../src/wxWidgets/include/wx/os2/pen.h \
		../src/wxWidgets/include/wx/qt/pen.h \
		../src/wxWidgets/include/wx/affinematrix2d.h \
		../src/wxWidgets/include/wx/affinematrix2dbase.h \
		../src/wxWidgets/include/wx/geometry.h \
		../src/wxWidgets/include/wx/cocoa/window.h \
		../src/wxWidgets/include/wx/cocoa/NSView.h \
		../src/wxWidgets/include/wx/cocoa/ObjcAssociate.h \
		../src/wxWidgets/include/wx/os2/window.h \
		../src/wxWidgets/include/wx/qt/window.h \
		../src/wxWidgets/include/wx/qt/pointer_qt.h \
		../qt/5.2.1/android_armv5/include/QtCore/QPointer \
		../qt/5.2.1/android_armv5/include/QtCore/qpointer.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/QWidget \
		../qt/5.2.1/android_armv5/include/QtWidgets/QScrollBar \
		../qt/5.2.1/android_armv5/include/QtWidgets/qscrollbar.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/qabstractslider.h \
		../src/wxWidgets/include/wx/univ/window.h \
		../src/wxWidgets/include/wx/msw/wrapcdlg.h \
		../src/wxWidgets/include/wx/mgl/private.h \
		../src/wxWidgets/include/wx/ioswrap.h \
		../src/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/iostream \
		../src/wxWidgets/include/wx/wx.h \
		../src/wxWidgets/include/wx/app.h \
		../src/wxWidgets/include/wx/build.h \
		../src/wxWidgets/include/wx/cmdargs.h \
		../src/wxWidgets/include/wx/init.h \
		../src/wxWidgets/include/wx/unix/app.h \
		../src/wxWidgets/include/wx/palmos/app.h \
		../src/wxWidgets/include/wx/icon.h \
		../src/wxWidgets/include/wx/iconloc.h \
		../src/wxWidgets/include/wx/generic/icon.h \
		../src/wxWidgets/include/wx/msw/icon.h \
		../src/wxWidgets/include/wx/motif/icon.h \
		../src/wxWidgets/include/wx/osx/icon.h \
		../src/wxWidgets/include/wx/cocoa/icon.h \
		../src/wxWidgets/include/wx/os2/icon.h \
		../src/wxWidgets/include/wx/msw/app.h \
		../src/wxWidgets/include/wx/motif/app.h \
		../src/wxWidgets/include/wx/mgl/app.h \
		../src/wxWidgets/include/wx/frame.h \
		../src/wxWidgets/include/wx/toplevel.h \
		../src/wxWidgets/include/wx/nonownedwnd.h \
		../src/wxWidgets/include/wx/dfb/nonownedwnd.h \
		../src/wxWidgets/include/wx/osx/nonownedwnd.h \
		../src/wxWidgets/include/wx/iconbndl.h \
		../src/wxWidgets/include/wx/containr.h \
		../src/wxWidgets/include/wx/weakref.h \
		../src/wxWidgets/include/wx/meta/int2type.h \
		../src/wxWidgets/include/wx/palmos/toplevel.h \
		../src/wxWidgets/include/wx/msw/toplevel.h \
		../src/wxWidgets/include/wx/gtk/toplevel.h \
		../src/wxWidgets/include/wx/gtk1/toplevel.h \
		../src/wxWidgets/include/wx/x11/toplevel.h \
		../src/wxWidgets/include/wx/mgl/toplevel.h \
		../src/wxWidgets/include/wx/dfb/toplevel.h \
		../src/wxWidgets/include/wx/osx/toplevel.h \
		../src/wxWidgets/include/wx/cocoa/toplevel.h \
		../src/wxWidgets/include/wx/cocoa/NSWindow.h \
		../src/wxWidgets/include/wx/os2/toplevel.h \
		../src/wxWidgets/include/wx/motif/toplevel.h \
		../src/wxWidgets/include/wx/qt/toplevel.h \
		../src/wxWidgets/include/wx/univ/toplevel.h \
		../src/wxWidgets/include/wx/univ/inpcons.h \
		../src/wxWidgets/include/wx/univ/inphand.h \
		../src/wxWidgets/include/wx/statusbr.h \
		../src/wxWidgets/include/wx/control.h \
		../src/wxWidgets/include/wx/univ/control.h \
		../src/wxWidgets/include/wx/palmos/control.h \
		../src/wxWidgets/include/wx/msw/control.h \
		../src/wxWidgets/include/wx/motif/control.h \
		../src/wxWidgets/include/wx/gtk/control.h \
		../src/wxWidgets/include/wx/gtk1/control.h \
		../src/wxWidgets/include/wx/osx/control.h \
		../src/wxWidgets/include/wx/cocoa/control.h \
		../src/wxWidgets/include/wx/cocoa/NSControl.h \
		../src/wxWidgets/include/wx/os2/control.h \
		../src/wxWidgets/include/wx/qt/control.h \
		../src/wxWidgets/include/wx/univ/statusbr.h \
		../src/wxWidgets/include/wx/palmos/statusbr.h \
		../src/wxWidgets/include/wx/msw/statusbar.h \
		../src/wxWidgets/include/wx/tooltip.h \
		../src/wxWidgets/include/wx/msw/tooltip.h \
		../src/wxWidgets/include/wx/gtk/tooltip.h \
		../src/wxWidgets/include/wx/gtk1/tooltip.h \
		../src/wxWidgets/include/wx/osx/tooltip.h \
		../src/wxWidgets/include/wx/cocoa/tooltip.h \
		../src/wxWidgets/include/wx/os2/tooltip.h \
		../src/wxWidgets/include/wx/qt/tooltip.h \
		../src/wxWidgets/include/wx/generic/statusbr.h \
		../src/wxWidgets/include/wx/osx/statusbr.h \
		../src/wxWidgets/include/wx/qt/statusbar.h \
		../src/wxWidgets/include/wx/qt/winevent_qt.h \
		../src/wxWidgets/include/wx/qt/converter.h \
		../qt/5.2.1/android_armv5/include/QtCore/QEvent \
		../qt/5.2.1/android_armv5/include/QtGui/QPaintEvent \
		../qt/5.2.1/android_armv5/include/QtWidgets/QLabel \
		../qt/5.2.1/android_armv5/include/QtWidgets/qlabel.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/qframe.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/QStatusBar \
		../qt/5.2.1/android_armv5/include/QtWidgets/qstatusbar.h \
		../src/wxWidgets/include/wx/univ/frame.h \
		../src/wxWidgets/include/wx/palmos/frame.h \
		../src/wxWidgets/include/wx/msw/frame.h \
		../src/wxWidgets/include/wx/gtk/frame.h \
		../src/wxWidgets/include/wx/gtk1/frame.h \
		../src/wxWidgets/include/wx/motif/frame.h \
		../src/wxWidgets/include/wx/osx/frame.h \
		../src/wxWidgets/include/wx/toolbar.h \
		../src/wxWidgets/include/wx/tbarbase.h \
		../src/wxWidgets/include/wx/univ/toolbar.h \
		../src/wxWidgets/include/wx/button.h \
		../src/wxWidgets/include/wx/anybutton.h \
		../src/wxWidgets/include/wx/msw/anybutton.h \
		../src/wxWidgets/include/wx/gtk/anybutton.h \
		../src/wxWidgets/include/wx/osx/anybutton.h \
		../src/wxWidgets/include/wx/univ/button.h \
		../src/wxWidgets/include/wx/msw/button.h \
		../src/wxWidgets/include/wx/motif/button.h \
		../src/wxWidgets/include/wx/gtk/button.h \
		../src/wxWidgets/include/wx/gtk1/button.h \
		../src/wxWidgets/include/wx/osx/button.h \
		../src/wxWidgets/include/wx/cocoa/button.h \
		../src/wxWidgets/include/wx/cocoa/NSButton.h \
		../src/wxWidgets/include/wx/cocoa/ObjcRef.h \
		../src/wxWidgets/include/wx/os2/button.h \
		../src/wxWidgets/include/wx/palmos/button.h \
		../src/wxWidgets/include/wx/qt/button.h \
		../src/wxWidgets/include/wx/qt/button_qt.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/QPushButton \
		../qt/5.2.1/android_armv5/include/QtWidgets/qpushbutton.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/qabstractbutton.h \
		../qt/5.2.1/android_armv5/include/QtGui/qicon.h \
		../src/wxWidgets/include/wx/palmos/toolbar.h \
		../src/wxWidgets/include/wx/msw/toolbar.h \
		../src/wxWidgets/include/wx/imaglist.h \
		../src/wxWidgets/include/wx/generic/imaglist.h \
		../src/wxWidgets/include/wx/msw/imaglist.h \
		../src/wxWidgets/include/wx/osx/imaglist.h \
		../src/wxWidgets/include/wx/palmos/imaglist.h \
		../src/wxWidgets/include/wx/msw/wince/tbarwce.h \
		../src/wxWidgets/include/wx/motif/toolbar.h \
		../src/wxWidgets/include/wx/gtk/toolbar.h \
		../src/wxWidgets/include/wx/gtk1/toolbar.h \
		../src/wxWidgets/include/wx/osx/toolbar.h \
		../src/wxWidgets/include/wx/cocoa/toolbar.h \
		../src/wxWidgets/include/wx/os2/toolbar.h \
		../src/wxWidgets/include/wx/timer.h \
		../src/wxWidgets/include/wx/stopwatch.h \
		../src/wxWidgets/include/wx/qt/toolbar.h \
		../src/wxWidgets/include/wx/cocoa/frame.h \
		../src/wxWidgets/include/wx/os2/frame.h \
		../src/wxWidgets/include/wx/os2/wxrsc.h \
		../src/wxWidgets/include/wx/qt/frame.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/QMainWindow \
		../qt/5.2.1/android_armv5/include/QtWidgets/qmainwindow.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/qtabwidget.h \
		../src/wxWidgets/include/wx/vidmode.h \
		../src/wxWidgets/include/wx/dfb/app.h \
		../src/wxWidgets/include/wx/gtk/app.h \
		../src/wxWidgets/include/wx/gtk1/app.h \
		../src/wxWidgets/include/wx/x11/app.h \
		../src/wxWidgets/include/wx/osx/app.h \
		../src/wxWidgets/include/wx/cocoa/app.h \
		../src/wxWidgets/include/wx/os2/app.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/sys/ioctl.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/linux/ioctl.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/asm/ioctl.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/asm-generic/ioctl.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/asm/ioctls.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/asm/termbits.h \
		../src/android-ndk-r9d/platforms/android-9/arch-arm/usr/include/sys/ioctl_compat.h \
		../src/wxWidgets/include/wx/qt/app.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/QApplication \
		../qt/5.2.1/android_armv5/include/QtWidgets/qapplication.h \
		../qt/5.2.1/android_armv5/include/QtCore/qcoreapplication.h \
		../qt/5.2.1/android_armv5/include/QtCore/qeventloop.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/qdesktopwidget.h \
		../qt/5.2.1/android_armv5/include/QtGui/qguiapplication.h \
		../qt/5.2.1/android_armv5/include/QtGui/qinputmethod.h \
		../src/wxWidgets/include/wx/univ/theme.h \
		../src/wxWidgets/include/wx/module.h \
		../src/wxWidgets/include/wx/panel.h \
		../src/wxWidgets/include/wx/univ/panel.h \
		../src/wxWidgets/include/wx/msw/panel.h \
		../src/wxWidgets/include/wx/generic/panelg.h \
		../src/wxWidgets/include/wx/dcclient.h \
		../src/wxWidgets/include/wx/dcmemory.h \
		../src/wxWidgets/include/wx/dcprint.h \
		../src/wxWidgets/include/wx/dcscreen.h \
		../src/wxWidgets/include/wx/menuitem.h \
		../src/wxWidgets/include/wx/univ/menuitem.h \
		../src/wxWidgets/include/wx/palmos/menuitem.h \
		../src/wxWidgets/include/wx/ownerdrw.h \
		../src/wxWidgets/include/wx/msw/ownerdrw.h \
		../src/wxWidgets/include/wx/os2/ownerdrw.h \
		../src/wxWidgets/include/wx/msw/menuitem.h \
		../src/wxWidgets/include/wx/motif/menuitem.h \
		../src/wxWidgets/include/wx/gtk/menuitem.h \
		../src/wxWidgets/include/wx/gtk1/menuitem.h \
		../src/wxWidgets/include/wx/osx/menuitem.h \
		../src/wxWidgets/include/wx/cocoa/menuitem.h \
		../src/wxWidgets/include/wx/os2/menuitem.h \
		../src/wxWidgets/include/wx/qt/menuitem.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/QAction \
		../qt/5.2.1/android_armv5/include/QtWidgets/qaction.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/qactiongroup.h \
		../src/wxWidgets/include/wx/menu.h \
		../src/wxWidgets/include/wx/univ/menu.h \
		../src/wxWidgets/include/wx/palmos/menu.h \
		../src/wxWidgets/include/wx/msw/menu.h \
		../src/wxWidgets/include/wx/motif/menu.h \
		../src/wxWidgets/include/wx/gtk/menu.h \
		../src/wxWidgets/include/wx/gtk1/menu.h \
		../src/wxWidgets/include/wx/osx/menu.h \
		../src/wxWidgets/include/wx/cocoa/menu.h \
		../src/wxWidgets/include/wx/cocoa/NSMenu.h \
		../src/wxWidgets/include/wx/os2/menu.h \
		../src/wxWidgets/include/wx/qt/menu.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/QMenu \
		../qt/5.2.1/android_armv5/include/QtWidgets/qmenu.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/QMenuBar \
		../qt/5.2.1/android_armv5/include/QtWidgets/qmenubar.h \
		../src/wxWidgets/include/wx/dialog.h \
		../src/wxWidgets/include/wx/univ/dialog.h \
		../src/wxWidgets/include/wx/palmos/dialog.h \
		../src/wxWidgets/include/wx/msw/dialog.h \
		../src/wxWidgets/include/wx/motif/dialog.h \
		../src/wxWidgets/include/wx/gtk/dialog.h \
		../src/wxWidgets/include/wx/gtk1/dialog.h \
		../src/wxWidgets/include/wx/osx/dialog.h \
		../src/wxWidgets/include/wx/cocoa/dialog.h \
		../src/wxWidgets/include/wx/cocoa/NSPanel.h \
		../src/wxWidgets/include/wx/os2/dialog.h \
		../src/wxWidgets/include/wx/qt/dialog.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/QDialog \
		../qt/5.2.1/android_armv5/include/QtWidgets/qdialog.h \
		../src/wxWidgets/include/wx/msgdlg.h \
		../src/wxWidgets/include/wx/stockitem.h \
		../src/wxWidgets/include/wx/generic/msgdlgg.h \
		../src/wxWidgets/include/wx/cocoa/msgdlg.h \
		../src/wxWidgets/include/wx/palmos/msgdlg.h \
		../src/wxWidgets/include/wx/msw/msgdlg.h \
		../src/wxWidgets/include/wx/motif/msgdlg.h \
		../src/wxWidgets/include/wx/gtk/msgdlg.h \
		../src/wxWidgets/include/wx/osx/msgdlg.h \
		../src/wxWidgets/include/wx/os2/msgdlg.h \
		../src/wxWidgets/include/wx/qt/msgdlg.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/QMessageBox \
		../qt/5.2.1/android_armv5/include/QtWidgets/qmessagebox.h \
		../src/wxWidgets/include/wx/dataobj.h \
		../src/wxWidgets/include/wx/msw/ole/dataform.h \
		../src/wxWidgets/include/wx/motif/dataform.h \
		../src/wxWidgets/include/wx/gtk/dataform.h \
		../src/wxWidgets/include/wx/gtk1/dataform.h \
		../src/wxWidgets/include/wx/x11/dataform.h \
		../src/wxWidgets/include/wx/osx/dataform.h \
		../src/wxWidgets/include/wx/cocoa/dataform.h \
		../src/wxWidgets/include/wx/os2/dataform.h \
		../src/wxWidgets/include/wx/qt/dataform.h \
		../src/wxWidgets/include/wx/msw/ole/dataobj.h \
		../src/wxWidgets/include/wx/motif/dataobj.h \
		../src/wxWidgets/include/wx/x11/dataobj.h \
		../src/wxWidgets/include/wx/gtk/dataobj.h \
		../src/wxWidgets/include/wx/gtk1/dataobj.h \
		../src/wxWidgets/include/wx/osx/dataobj.h \
		../src/wxWidgets/include/wx/cocoa/dataobj.h \
		../src/wxWidgets/include/wx/os2/dataobj.h \
		../src/wxWidgets/include/wx/qt/dataobj.h \
		../src/wxWidgets/include/wx/msw/ole/dataobj2.h \
		../src/wxWidgets/include/wx/gtk/dataobj2.h \
		../src/wxWidgets/include/wx/gtk1/dataobj2.h \
		../src/wxWidgets/include/wx/x11/dataobj2.h \
		../src/wxWidgets/include/wx/motif/dataobj2.h \
		../src/wxWidgets/include/wx/osx/dataobj2.h \
		../src/wxWidgets/include/wx/cocoa/dataobj2.h \
		../src/wxWidgets/include/wx/os2/dataobj2.h \
		../src/wxWidgets/include/wx/qt/dataobj2.h \
		../src/wxWidgets/include/wx/ctrlsub.h \
		../src/wxWidgets/include/wx/msw/ctrlsub.h \
		../src/wxWidgets/include/wx/motif/ctrlsub.h \
		../src/wxWidgets/include/wx/generic/ctrlsub.h \
		../src/wxWidgets/include/wx/qt/ctrlsub.h \
		../src/wxWidgets/include/wx/bmpbuttn.h \
		../src/wxWidgets/include/wx/univ/bmpbuttn.h \
		../src/wxWidgets/include/wx/msw/bmpbuttn.h \
		../src/wxWidgets/include/wx/motif/bmpbuttn.h \
		../src/wxWidgets/include/wx/motif/bmpmotif.h \
		../src/wxWidgets/include/wx/gtk/bmpbuttn.h \
		../src/wxWidgets/include/wx/gtk1/bmpbuttn.h \
		../src/wxWidgets/include/wx/osx/bmpbuttn.h \
		../src/wxWidgets/include/wx/cocoa/bmpbuttn.h \
		../src/wxWidgets/include/wx/os2/bmpbuttn.h \
		../src/wxWidgets/include/wx/palmos/bmpbuttn.h \
		../src/wxWidgets/include/wx/qt/bmpbuttn.h \
		../src/wxWidgets/include/wx/checkbox.h \
		../src/wxWidgets/include/wx/univ/checkbox.h \
		../src/wxWidgets/include/wx/msw/checkbox.h \
		../src/wxWidgets/include/wx/motif/checkbox.h \
		../src/wxWidgets/include/wx/gtk/checkbox.h \
		../src/wxWidgets/include/wx/gtk1/checkbox.h \
		../src/wxWidgets/include/wx/osx/checkbox.h \
		../src/wxWidgets/include/wx/cocoa/checkbox.h \
		../src/wxWidgets/include/wx/os2/checkbox.h \
		../src/wxWidgets/include/wx/palmos/checkbox.h \
		../src/wxWidgets/include/wx/qt/checkbox.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/QCheckBox \
		../qt/5.2.1/android_armv5/include/QtWidgets/qcheckbox.h \
		../src/wxWidgets/include/wx/checklst.h \
		../src/wxWidgets/include/wx/listbox.h \
		../src/wxWidgets/include/wx/univ/listbox.h \
		../src/wxWidgets/include/wx/scrolwin.h \
		../src/wxWidgets/include/wx/gtk/scrolwin.h \
		../src/wxWidgets/include/wx/gtk1/scrolwin.h \
		../src/wxWidgets/include/wx/generic/scrolwin.h \
		../src/wxWidgets/include/wx/msw/listbox.h \
		../src/wxWidgets/include/wx/motif/listbox.h \
		../src/wxWidgets/include/wx/gtk/listbox.h \
		../src/wxWidgets/include/wx/gtk1/listbox.h \
		../src/wxWidgets/include/wx/osx/listbox.h \
		../src/wxWidgets/include/wx/os2/listbox.h \
		../src/wxWidgets/include/wx/cocoa/listbox.h \
		../src/wxWidgets/include/wx/cocoa/NSTableView.h \
		../src/wxWidgets/include/wx/qt/listbox.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/QListWidget \
		../qt/5.2.1/android_armv5/include/QtWidgets/qlistwidget.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/qlistview.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/qabstractitemview.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/qabstractscrollarea.h \
		../qt/5.2.1/android_armv5/include/QtCore/qabstractitemmodel.h \
		../qt/5.2.1/android_armv5/include/QtCore/qitemselectionmodel.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/qabstractitemdelegate.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/qstyleoption.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/qabstractspinbox.h \
		../qt/5.2.1/android_armv5/include/QtGui/qvalidator.h \
		../qt/5.2.1/android_armv5/include/QtCore/qregularexpression.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/qslider.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/qstyle.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/qtabbar.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/qrubberband.h \
		../src/wxWidgets/include/wx/univ/checklst.h \
		../src/wxWidgets/include/wx/msw/wince/checklst.h \
		../src/wxWidgets/include/wx/msw/checklst.h \
		../src/wxWidgets/include/wx/motif/checklst.h \
		../src/wxWidgets/include/wx/gtk/checklst.h \
		../src/wxWidgets/include/wx/gtk1/checklst.h \
		../src/wxWidgets/include/wx/osx/checklst.h \
		../src/wxWidgets/include/wx/cocoa/checklst.h \
		../src/wxWidgets/include/wx/os2/checklst.h \
		../src/wxWidgets/include/wx/qt/checklst.h \
		../src/wxWidgets/include/wx/choice.h \
		../src/wxWidgets/include/wx/univ/choice.h \
		../src/wxWidgets/include/wx/combobox.h \
		../src/wxWidgets/include/wx/textentry.h \
		../src/wxWidgets/include/wx/gtk/textentry.h \
		../src/wxWidgets/include/wx/osx/textentry.h \
		../src/wxWidgets/include/wx/msw/textentry.h \
		../src/wxWidgets/include/wx/motif/textentry.h \
		../src/wxWidgets/include/wx/os2/textentry.h \
		../src/wxWidgets/include/wx/qt/textentry.h \
		../src/wxWidgets/include/wx/univ/combobox.h \
		../src/wxWidgets/include/wx/combo.h \
		../src/wxWidgets/include/wx/renderer.h \
		../src/wxWidgets/include/wx/msw/combo.h \
		../src/wxWidgets/include/wx/generic/combo.h \
		../src/wxWidgets/include/wx/dcbuffer.h \
		../src/wxWidgets/include/wx/msw/combobox.h \
		../src/wxWidgets/include/wx/motif/combobox.h \
		../src/wxWidgets/include/wx/gtk/combobox.h \
		../src/wxWidgets/include/wx/gtk1/combobox.h \
		../src/wxWidgets/include/wx/osx/combobox.h \
		../src/wxWidgets/include/wx/textctrl.h \
		../src/wxWidgets/include/wx/x11/textctrl.h \
		../src/wxWidgets/include/wx/univ/textctrl.h \
		../src/wxWidgets/include/wx/msw/wince/textctrlce.h \
		../src/wxWidgets/include/wx/msw/textctrl.h \
		../src/wxWidgets/include/wx/motif/textctrl.h \
		../src/wxWidgets/include/wx/gtk/textctrl.h \
		../src/wxWidgets/include/wx/gtk1/textctrl.h \
		../src/wxWidgets/include/wx/osx/textctrl.h \
		../src/wxWidgets/include/wx/cocoa/textctrl.h \
		../src/wxWidgets/include/wx/cocoa/NSTextField.h \
		../src/wxWidgets/include/wx/os2/textctrl.h \
		../src/wxWidgets/include/wx/palmos/textctrl.h \
		../src/wxWidgets/include/wx/qt/textctrl.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/QTextEdit \
		../qt/5.2.1/android_armv5/include/QtWidgets/qtextedit.h \
		../qt/5.2.1/android_armv5/include/QtGui/qtextdocument.h \
		../qt/5.2.1/android_armv5/include/QtGui/qtextoption.h \
		../qt/5.2.1/android_armv5/include/QtGui/qtextcursor.h \
		../qt/5.2.1/android_armv5/include/QtGui/qtextformat.h \
		../qt/5.2.1/android_armv5/include/QtGui/qpen.h \
		../src/wxWidgets/include/wx/cocoa/combobox.h \
		../src/wxWidgets/include/wx/os2/combobox.h \
		../src/wxWidgets/include/wx/qt/combobox.h \
		../src/wxWidgets/include/wx/qt/combobox_qt.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/QComboBox \
		../qt/5.2.1/android_armv5/include/QtWidgets/qcombobox.h \
		../src/wxWidgets/include/wx/msw/wince/choicece.h \
		../src/wxWidgets/include/wx/msw/choice.h \
		../src/wxWidgets/include/wx/motif/choice.h \
		../src/wxWidgets/include/wx/gtk/choice.h \
		../src/wxWidgets/include/wx/gtk1/choice.h \
		../src/wxWidgets/include/wx/osx/choice.h \
		../src/wxWidgets/include/wx/cocoa/choice.h \
		../src/wxWidgets/include/wx/os2/choice.h \
		../src/wxWidgets/include/wx/palmos/choice.h \
		../src/wxWidgets/include/wx/qt/choice.h \
		../src/wxWidgets/include/wx/scrolbar.h \
		../src/wxWidgets/include/wx/univ/scrolbar.h \
		../src/wxWidgets/include/wx/univ/scrarrow.h \
		../src/wxWidgets/include/wx/msw/scrolbar.h \
		../src/wxWidgets/include/wx/motif/scrolbar.h \
		../src/wxWidgets/include/wx/gtk/scrolbar.h \
		../src/wxWidgets/include/wx/gtk1/scrolbar.h \
		../src/wxWidgets/include/wx/osx/scrolbar.h \
		../src/wxWidgets/include/wx/cocoa/scrolbar.h \
		../src/wxWidgets/include/wx/cocoa/NSScroller.h \
		../src/wxWidgets/include/wx/os2/scrolbar.h \
		../src/wxWidgets/include/wx/qt/scrolbar.h \
		../src/wxWidgets/include/wx/stattext.h \
		../src/wxWidgets/include/wx/univ/stattext.h \
		../src/wxWidgets/include/wx/generic/stattextg.h \
		../src/wxWidgets/include/wx/msw/stattext.h \
		../src/wxWidgets/include/wx/motif/stattext.h \
		../src/wxWidgets/include/wx/gtk/stattext.h \
		../src/wxWidgets/include/wx/gtk1/stattext.h \
		../src/wxWidgets/include/wx/osx/stattext.h \
		../src/wxWidgets/include/wx/cocoa/stattext.h \
		../src/wxWidgets/include/wx/os2/stattext.h \
		../src/wxWidgets/include/wx/palmos/stattext.h \
		../src/wxWidgets/include/wx/qt/stattext.h \
		../src/wxWidgets/include/wx/statbmp.h \
		../src/wxWidgets/include/wx/univ/statbmp.h \
		../src/wxWidgets/include/wx/msw/statbmp.h \
		../src/wxWidgets/include/wx/motif/statbmp.h \
		../src/wxWidgets/include/wx/gtk/statbmp.h \
		../src/wxWidgets/include/wx/gtk1/statbmp.h \
		../src/wxWidgets/include/wx/osx/statbmp.h \
		../src/wxWidgets/include/wx/osx/carbon/statbmp.h \
		../src/wxWidgets/include/wx/generic/statbmpg.h \
		../src/wxWidgets/include/wx/cocoa/statbmp.h \
		../src/wxWidgets/include/wx/os2/statbmp.h \
		../src/wxWidgets/include/wx/qt/statbmp.h \
		../src/wxWidgets/include/wx/statbox.h \
		../src/wxWidgets/include/wx/univ/statbox.h \
		../src/wxWidgets/include/wx/msw/statbox.h \
		../src/wxWidgets/include/wx/motif/statbox.h \
		../src/wxWidgets/include/wx/gtk/statbox.h \
		../src/wxWidgets/include/wx/gtk1/statbox.h \
		../src/wxWidgets/include/wx/osx/statbox.h \
		../src/wxWidgets/include/wx/cocoa/statbox.h \
		../src/wxWidgets/include/wx/cocoa/NSBox.h \
		../src/wxWidgets/include/wx/os2/statbox.h \
		../src/wxWidgets/include/wx/qt/statbox.h \
		../src/wxWidgets/include/wx/qt/groupbox_qt.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/QGroupBox \
		../qt/5.2.1/android_armv5/include/QtWidgets/qgroupbox.h \
		../src/wxWidgets/include/wx/radiobox.h \
		../src/wxWidgets/include/wx/univ/radiobox.h \
		../src/wxWidgets/include/wx/msw/radiobox.h \
		../src/wxWidgets/include/wx/motif/radiobox.h \
		../src/wxWidgets/include/wx/gtk/radiobox.h \
		../src/wxWidgets/include/wx/gtk1/radiobox.h \
		../src/wxWidgets/include/wx/osx/radiobox.h \
		../src/wxWidgets/include/wx/cocoa/radiobox.h \
		../src/wxWidgets/include/wx/os2/radiobox.h \
		../src/wxWidgets/include/wx/palmos/radiobox.h \
		../src/wxWidgets/include/wx/qt/radiobox.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/QButtonGroup \
		../qt/5.2.1/android_armv5/include/QtWidgets/qbuttongroup.h \
		../src/wxWidgets/include/wx/radiobut.h \
		../src/wxWidgets/include/wx/univ/radiobut.h \
		../src/wxWidgets/include/wx/msw/radiobut.h \
		../src/wxWidgets/include/wx/motif/radiobut.h \
		../src/wxWidgets/include/wx/gtk/radiobut.h \
		../src/wxWidgets/include/wx/gtk1/radiobut.h \
		../src/wxWidgets/include/wx/osx/radiobut.h \
		../src/wxWidgets/include/wx/cocoa/radiobut.h \
		../src/wxWidgets/include/wx/os2/radiobut.h \
		../src/wxWidgets/include/wx/palmos/radiobut.h \
		../src/wxWidgets/include/wx/qt/radiobut.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/QRadioButton \
		../qt/5.2.1/android_armv5/include/QtWidgets/qradiobutton.h \
		../src/wxWidgets/include/wx/slider.h \
		../src/wxWidgets/include/wx/univ/slider.h \
		../src/wxWidgets/include/wx/univ/scrthumb.h \
		../src/wxWidgets/include/wx/msw/slider.h \
		../src/wxWidgets/include/wx/motif/slider.h \
		../src/wxWidgets/include/wx/gtk/slider.h \
		../src/wxWidgets/include/wx/gtk1/slider.h \
		../src/wxWidgets/include/wx/osx/slider.h \
		../src/wxWidgets/include/wx/cocoa/slider.h \
		../src/wxWidgets/include/wx/cocoa/NSSlider.h \
		../src/wxWidgets/include/wx/os2/slider.h \
		../src/wxWidgets/include/wx/palmos/slider.h \
		../src/wxWidgets/include/wx/qt/slider.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/QSlider \
		../src/wxWidgets/include/wx/gauge.h \
		../src/wxWidgets/include/wx/univ/gauge.h \
		../src/wxWidgets/include/wx/msw/gauge.h \
		../src/wxWidgets/include/wx/motif/gauge.h \
		../src/wxWidgets/include/wx/gtk/gauge.h \
		../src/wxWidgets/include/wx/gtk1/gauge.h \
		../src/wxWidgets/include/wx/osx/gauge.h \
		../src/wxWidgets/include/wx/cocoa/gauge.h \
		../src/wxWidgets/include/wx/os2/gauge.h \
		../src/wxWidgets/include/wx/qt/gauge.h \
		../qt/5.2.1/android_armv5/include/QtWidgets/QProgressBar \
		../qt/5.2.1/android_armv5/include/QtWidgets/qprogressbar.h \
		../src/wxWidgets/include/wx/dirdlg.h \
		../src/wxWidgets/include/wx/generic/dirdlgg.h \
		../src/wxWidgets/include/wx/msw/dirdlg.h \
		../src/wxWidgets/include/wx/gtk/dirdlg.h \
		../src/wxWidgets/include/wx/osx/dirdlg.h \
		../src/wxWidgets/include/wx/cocoa/dirdlg.h \
		../src/wxWidgets/include/wx/qt/dirdlg.h \
		../src/wxWidgets/include/wx/layout.h \
		../src/wxWidgets/include/wx/sizer.h \
		../src/wxWidgets/include/wx/choicdlg.h \
		../src/wxWidgets/include/wx/generic/choicdgg.h \
		../src/wxWidgets/include/wx/textdlg.h \
		../src/wxWidgets/include/wx/qt/textdlg.h \
		../src/wxWidgets/include/wx/generic/textdlgg.h \
		../src/wxWidgets/include/wx/valtext.h \
		../src/wxWidgets/include/wx/filedlg.h \
		../src/wxWidgets/include/wx/generic/filedlgg.h \
		../src/wxWidgets/include/wx/listctrl.h \
		../src/wxWidgets/include/wx/listbase.h \
		../src/wxWidgets/include/wx/msw/listctrl.h \
		../src/wxWidgets/include/wx/osx/listctrl.h \
		../src/wxWidgets/include/wx/generic/listctrl.h \
		../src/wxWidgets/include/wx/qt/listctrl.h \
		../src/wxWidgets/include/wx/artprov.h \
		../src/wxWidgets/include/wx/generic/filectrlg.h \
		../src/wxWidgets/include/wx/filectrl.h \
		../src/wxWidgets/include/wx/gtk/filectrl.h \
		../src/wxWidgets/include/wx/filename.h \
		../src/wxWidgets/include/wx/file.h \
		../src/wxWidgets/include/wx/msw/filedlg.h \
		../src/wxWidgets/include/wx/motif/filedlg.h \
		../src/wxWidgets/include/wx/gtk/filedlg.h \
		../src/wxWidgets/include/wx/gtk1/filedlg.h \
		../src/wxWidgets/include/wx/osx/filedlg.h \
		../src/wxWidgets/include/wx/cocoa/filedlg.h \
		../src/wxWidgets/include/wx/os2/filedlg.h \
		../src/wxWidgets/include/wx/qt/filedlg.h \
		../src/wxWidgets/include/wx/mdi.h \
		../src/wxWidgets/include/wx/generic/mdig.h \
		../src/wxWidgets/include/wx/msw/mdi.h \
		../src/wxWidgets/include/wx/gtk/mdi.h \
		../src/wxWidgets/include/wx/gtk1/mdi.h \
		../src/wxWidgets/include/wx/osx/mdi.h \
		../src/wxWidgets/include/wx/cocoa/mdi.h \
		../src/wxWidgets/include/wx/qt/mdi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minimal.o minimal.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/libs/armeabi/ || mkdir -p $(INSTALL_ROOT)/libs/armeabi/
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/libs/armeabi/$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/libs/armeabi/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/libs/armeabi/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

